owner: rnateam
name: rnabob
description: Fast Pattern searching for RNA secondary structures
long_description: Fast Pattern searching for RNA secondary structures
categories:
  - RNA
remote_repository_url: https://github.com/eteriSokhoyan/galaxytools/tree/master/tools/rna_tools/rnabob
